# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'code-editor.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(898, 818)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.options = QtWidgets.QLabel(self.centralwidget)
        self.options.setGeometry(QtCore.QRect(0, 0, 51, 871))
        self.options.setStyleSheet("background:rgb(86, 86, 86);")
        self.options.setText("")
        self.options.setObjectName("options")
        self.file_manager = QtWidgets.QLabel(self.centralwidget)
        self.file_manager.setGeometry(QtCore.QRect(50, 0, 191, 871))
        self.file_manager.setStyleSheet("background:rgb(54, 54, 54);")
        self.file_manager.setText("")
        self.file_manager.setObjectName("file_manager")
        self.file_names = QtWidgets.QLabel(self.centralwidget)
        self.file_names.setGeometry(QtCore.QRect(50, 19, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.file_names.setFont(font)
        self.file_names.setStyleSheet("background:rgb(29, 29, 29);\n"
"color:\"white\";\n"
"padding: 0px 5px;")
        self.file_names.setWordWrap(True)
        self.file_names.setIndent(1)
        self.file_names.setObjectName("file_names")
        self.workspace = QtWidgets.QTextEdit(self.centralwidget)
        self.workspace.setGeometry(QtCore.QRect(233, 0, 1911, 871))
        self.workspace.setStyleSheet("background:rgb(27, 27, 27);\n"
"padding: 28px 15px;\n"
"color: red;\n"
"font-size: 18px;")
        self.workspace.setObjectName("workspace")
        self.files = QtWidgets.QLabel(self.centralwidget)
        self.files.setGeometry(QtCore.QRect(0, 20, 51, 41))
        self.files.setStyleSheet("font-size: 20px;\n"
"image-size:10px 10px;")
        self.files.setText("")
        self.files.setPixmap(QtGui.QPixmap("../../../downloaded_images/renegane.png"))
        self.files.setWordWrap(False)
        self.files.setObjectName("files")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setAcceptDrops(False)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 898, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.menubar.setFont(font)
        self.menubar.setStyleSheet("background:rgb(91, 91, 91);")
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setStyleSheet("background: grey;\n"
"color: red;")
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.Logo = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Logo.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../downloaded_images/Sharingan.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Logo.setIcon(icon)
        self.Logo.setObjectName("Logo")
        MainWindow.setMenuBar(self.menubar)
        self.menubar.addAction(self.Logo.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.file_names.setText(_translate("MainWindow", "File name"))
        self.workspace.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:18px; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt;\"><br /></p></body></html>"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.Logo.setTitle(_translate("MainWindow", "Logo"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
